=== SergioOlabuenaga/eSport/Fase3/LM/Clasificacion2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="clasificacion" type="tipoclasificacion"/>
  <xs:complexType name="tipoclasificacion">
    <xs:sequence>
      <xs:element type="tipoequipos" name="equipos"/>
    </xs:sequence>
    <xs:attribute type="xs:ID" name="ID"/>
    <xs:attribute type="xs:date" name="fechaExpiracion"/>
  </xs:complexType>
  <xs:complexType name="tipoequipos">
    <xs:sequence>
      <xs:element type="tipoequipo" name="equipo" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tipoequipo">
    <xs:sequence>
      <xs:element type="tiponombre" name="nombre"/>
      <xs:element type="xs:integer" name="puntos"/>
      <xs:element type="xs:integer" name="posicion"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tiponombre">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:ID" name="ID"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== SergioOlabuenaga/eSport/Fase3/LM/Clasificacion2.xml
<?xml version="1.0" encoding="utf-8"?>
<clasificacion ID="C1" fechaExpiracion="2022-06-17" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Clasificacion2.xsd">
        <equipos>
            <equipo>
                <nombre ID="E1">equipo1</nombre>
                <puntos>9</puntos>
                <posicion>1</posicion>
            </equipo>
            <equipo>
                <nombre ID="E2">equipo2</nombre>
                <puntos>6</puntos>
                <posicion>2</posicion>
            </equipo>
            <equipo>
                <nombre ID="E3">equipo3</nombre>
                <puntos>3</puntos>
                <posicion>3</posicion>
            </equipo>
            <equipo>
                <nombre ID="E4">equipo4</nombre>
                <puntos>0</puntos>
                <posicion>4</posicion>
            </equipo>
        </equipos>
</clasificacion>
