=== SergioOlabuenaga/eSport/Fase3/LM/Jornadas.dtd
<!ELEMENT Jornadas (jornada+,fechaExpiracion)>
        <!ELEMENT fechaExpiracion (#PCDATA)>
        <!ELEMENT jornada (partido)+>
        <!ATTLIST jornada ID CDATA #REQUIRED>
        <!ATTLIST jornada fecha CDATA #REQUIRED>
        <!ELEMENT partido (equipo+, resultado)>
        <!ATTLIST partido ID CDATA #REQUIRED>
        <!ATTLIST partido hora CDATA #REQUIRED>
        <!ELEMENT equipo (#PCDATA)>
        <!ATTLIST equipo ID CDATA #REQUIRED>
        <!ELEMENT resultado (#PCDATA)>

=== SergioOlabuenaga/eSport/Fase3/LM/Jornadas.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Jornadas SYSTEM "Jornadas.dtd">
<Jornadas>
    <jornada ID="1" fecha="27/05/2022">
        <partido ID="1" hora="17:30">
            <equipo ID="1">equipo1</equipo>
            <equipo ID="2">equipo2</equipo>
            <resultado>3-2</resultado>
        </partido>
        <partido ID="2" hora="20:00">
            <equipo ID="3">equipo3</equipo>
            <equipo ID="4">equipo4</equipo>
            <resultado>3-2</resultado>
        </partido>
    </jornada>
    <jornada ID="2" fecha="03/06/2022">
        <partido ID="1" hora="13:00">
            <equipo ID="1">equipo1</equipo>
            <equipo ID="3">equipo3</equipo>
            <resultado>3-0</resultado>
        </partido>
        <partido ID="2" hora="18:30">
            <equipo ID="2">equipo2</equipo>
            <equipo ID="4">equipo4</equipo>
            <resultado>3-1</resultado>
        </partido>
    </jornada>
    <jornada ID="3" fecha="10/06/2022">
        <partido ID="1" hora="15:00">
            <equipo ID="1">equipo1</equipo>
            <equipo ID="4">equipo4</equipo>
            <resultado>3-1</resultado>
        </partido>
        <partido ID="2" hora="19:00">
            <equipo ID="2">equipo2</equipo>
            <equipo ID="3">equipo3</equipo>
            <resultado>3-2</resultado>
        </partido>
    </jornada>
    <fechaExpiracion>17/06/2022</fechaExpiracion>
</Jornadas>
